[package]
authors = ["Liam Woodward <liamowoodward@gmail.com>"]
edition = "2018"
name = "notes"
version = "0.1.0"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
directories = "2.0"
exitfailure = "0.5.1"
failure = "0.1.6"
rusqlite = { version = "0.21.0", features = ["chrono"] }
rust-crypto = "0.2"
structopt = "0.3"
text_io = "0.1.8"

serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.11"
