[package]
authors = ["Liam Woodward <liamowoodward@gmail.com>"]
edition = "2018"
name = "notes"
version = "0.2.1"

[dependencies]
anyhow = "1.0.31"
async-std = { version = "1.5.0", features = ["attributes"] }
bincode = "1.2.1"
chrono = { version = "0.4.10", features = ["serde"] }
colored = "1.9.3"
directories = "2.0"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3"
text_io = "0.1.8"
thiserror = "1.0.18"
