[package]
authors = ["Liam Woodward <liamowoodward@gmail.com>"]
edition = "2018"
name = "lib"
version = "0.2.0"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
directories = "2.0"
exitfailure = "0.5.1"
failure = "0.1.6"
sqlx = { version = "0.3", features = ["sqlite", "chrono"] }
structopt = "0.3"
text_io = "0.1.8"

serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.11"
