[package]
authors = ["Liam Woodward <liamowoodward@gmail.com>"]
edition = "2018"
name = "notes"
version = "0.2.0"

[dependencies]
chrono = "0.4.10"
directories = "2.0"
anyhow = "1.0.31"
thiserror = "1.0.17"
sqlx = { version = "0.3.5", features = ["macros", "sqlite", "chrono"] }
async-std = { version = "1.5.0", features = [ "attributes" ] }
structopt = "0.3"
text_io = "0.1.8"
