[package]
authors = ["Liam Woodward <liamowoodward@gmail.com>"]
edition = "2018"
name = "cli"
version = "0.1.0"

[dependencies]
lib = { path = "../lib" }

chrono = { version = "0.4", features = ["serde"] }
directories = "2.0"
exitfailure = "0.5.1"
failure = "0.1.6"
structopt = "0.3"
